version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    ports:
      - "port:80"  #前面的port改为你自己的端口
    environment:
      TZ: Asia/Shanghai  #时区，见http://php.net/timezones
      CRON_MIN: '3,33' #Cron job to refresh feeds at specified minutes
      FRESHRSS_ENV: development