version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 9004:8096
    volumes:
      - ./config:/config
      - /nas:/nas
    privileged: true
