services:
    mumble-server:
        image: mumblevoip/mumble-server:latest
        container_name: mumble-server
        hostname: mumble-server
        restart: on-failure
        environment:
            MUMBLE_SUPERUSER_PASSWORD: xxxxx
            MUMBLE_CUSTOM_CONFIG_FILE: /data/config.ini
        ports:
            - 64738:64738
            - 64738:64738/udp
#       expose:
#           - 6502